// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trhkbrxwtqhiqslmewpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyaGticnh3dHFoaXFzbG1ld3BpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTU0MDMsImV4cCI6MjA2NjY3MTQwM30.taCcYxZ1ZrSEinIL4f7OIUnFRtef29T5BiL0hnQ7VG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});